workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Build
        script: |
          cd "Flappy Bird"
          xcode-project build-ipa \
            --project FlappyBird.xcodeproj \
            --scheme FlappyBird
    artifacts:
      - build/ios/ipa/*.ipa
