name: Son Deneme

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Build
        run: |
          # Klasör adında ve Proje adında boşluk varsa şu şekilde yazmalısın:
          # "Kaynak Kod/Proje Adı.xcodeproj"
          xcodebuild archive \
            -project "Flappy Bird/Flappy Bird.xcodeproj" \
            -scheme "Flappy Bird" \
            -archivePath "Flappy Bird/Flappy Bird.xcarchive" \
            -destination "generic/platform=iOS" \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

