- name: Kütüphaneleri Hazırla ve Derle
  run: |
    # 1. Projenin olduğu klasöre git
    cd "Flappy Bird" 
    
    # 2. Eğer kütüphane kullanıyorsan pod install yap (yoksa geç)
    # pod install 

    # 3. Arşivi oluştur (Bu komut bittiğinde xcarchive oluşacak)
    xcodebuild -project "Flappy Bird.xcodeproj" \
               -scheme "Flappy Bird" \
               -configuration Release \
               -archivePath ./build/Projeniz.xcarchive \
               archive \
               CODE_SIGNING_ALLOWED=NO # Sertifikayı sonraki adımda basacağız
