name: iOS Build

on:
  push:
    branches: [ main ] # Kodları hangi branch'e atıyorsanız (main/master)

jobs:
  build:
    runs-on: macos-latest
    # TÜM KOMUTLARI BU KLASÖRDE ÇALIŞTIRIR
    defaults:
      run:
        working-directory: "Flappy Bird" 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Xcode Build
        run: |
          # Proje dosyanızın adı neyse onu yazın
          xcodebuild -project "Flappy Bird.xcodeproj" \
                     -scheme "Flappy Bird" \
                     -configuration Release \
                     -sdk iphoneos \
                     archive \
                     -archivePath "./Flappy Bird.xcarchive" \
                     CODE_SIGNING_ALLOWED=NO
